### ISSUE TITLE
Unable to perform any actions using YUM

### ISSUE THREAD

**Issue by jaiswal-prashant** [carlosCharz/installjenkinsaws#1]
Hi Carlos,

I tried launching linux EC-2 instance on AWS same as you told. But when I am trying to perform any actions using yum it is giving below error. Kindly help me.

root@ip-172-31-21-67 ec2-user]# yum list installed
Loaded plugins: priorities, update-motd, upgrade-helper
Could not retrieve mirrorlist http://repo.ap-south-1.amazonaws.com/latest/main/mirror.list error was
12: Timeout on http://repo.ap-south-1.amazonaws.com/latest/main/mirror.list: (28, 'Connection timed out after 5001 milliseconds')

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn-main/latest

**Comment by carlosCharz** [comment]
Hello @jaiswal-prashant I just logged in on my ec2 instance and perform: yum list installed. Everything seem to be ok. Have you tried turning on and off your ec2 instance? Does it say some specific package that they cannot retrieve because it seems something related to amazon. Try restarting ...

**Comment by jaiswal-prashant** [comment]
Hi Carlos,
I tried doing that but no luck. 
After I found that I have chosen the wrong region. I corrected to Oregon region and it worked.
